// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/message.proto

package com.jiang.framework.message;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface messageEnumOrBuilder extends
      // @@protoc_insertion_point(interface_extends:messageEnum)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code messageEnum}
   */
  public static final class messageEnum extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:messageEnum)
      messageEnumOrBuilder {
    // Use messageEnum.newBuilder() to construct.
    private messageEnum(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private messageEnum(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final messageEnum defaultInstance;
    public static messageEnum getDefaultInstance() {
      return defaultInstance;
    }

    public messageEnum getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private messageEnum(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jiang.framework.message.MessageProto.internal_static_messageEnum_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jiang.framework.message.MessageProto.internal_static_messageEnum_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jiang.framework.message.MessageProto.messageEnum.class, com.jiang.framework.message.MessageProto.messageEnum.Builder.class);
    }

    public static com.google.protobuf.Parser<messageEnum> PARSER =
        new com.google.protobuf.AbstractParser<messageEnum>() {
      public messageEnum parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new messageEnum(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<messageEnum> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code messageEnum.MessageID}
     */
    public enum MessageID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>C_USER_LOGIN = 10001;</code>
       */
      C_USER_LOGIN(0, 10001),
      /**
       * <code>S_USER_LOGIN = 10002;</code>
       */
      S_USER_LOGIN(1, 10002),
      ;

      /**
       * <code>C_USER_LOGIN = 10001;</code>
       */
      public static final int C_USER_LOGIN_VALUE = 10001;
      /**
       * <code>S_USER_LOGIN = 10002;</code>
       */
      public static final int S_USER_LOGIN_VALUE = 10002;


      public final int getNumber() { return value; }

      public static MessageID valueOf(int value) {
        switch (value) {
          case 10001: return C_USER_LOGIN;
          case 10002: return S_USER_LOGIN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MessageID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageID>() {
              public MessageID findValueByNumber(int number) {
                return MessageID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.jiang.framework.message.MessageProto.messageEnum.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageID[] VALUES = values();

      public static MessageID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MessageID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:messageEnum.MessageID)
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.jiang.framework.message.MessageProto.messageEnum parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jiang.framework.message.MessageProto.messageEnum parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jiang.framework.message.MessageProto.messageEnum parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jiang.framework.message.MessageProto.messageEnum parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jiang.framework.message.MessageProto.messageEnum parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jiang.framework.message.MessageProto.messageEnum parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.jiang.framework.message.MessageProto.messageEnum parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.jiang.framework.message.MessageProto.messageEnum parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.jiang.framework.message.MessageProto.messageEnum parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jiang.framework.message.MessageProto.messageEnum parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jiang.framework.message.MessageProto.messageEnum prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messageEnum}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:messageEnum)
        com.jiang.framework.message.MessageProto.messageEnumOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jiang.framework.message.MessageProto.internal_static_messageEnum_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jiang.framework.message.MessageProto.internal_static_messageEnum_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jiang.framework.message.MessageProto.messageEnum.class, com.jiang.framework.message.MessageProto.messageEnum.Builder.class);
      }

      // Construct using com.jiang.framework.message.MessageProto.messageEnum.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jiang.framework.message.MessageProto.internal_static_messageEnum_descriptor;
      }

      public com.jiang.framework.message.MessageProto.messageEnum getDefaultInstanceForType() {
        return com.jiang.framework.message.MessageProto.messageEnum.getDefaultInstance();
      }

      public com.jiang.framework.message.MessageProto.messageEnum build() {
        com.jiang.framework.message.MessageProto.messageEnum result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jiang.framework.message.MessageProto.messageEnum buildPartial() {
        com.jiang.framework.message.MessageProto.messageEnum result = new com.jiang.framework.message.MessageProto.messageEnum(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jiang.framework.message.MessageProto.messageEnum) {
          return mergeFrom((com.jiang.framework.message.MessageProto.messageEnum)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jiang.framework.message.MessageProto.messageEnum other) {
        if (other == com.jiang.framework.message.MessageProto.messageEnum.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jiang.framework.message.MessageProto.messageEnum parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jiang.framework.message.MessageProto.messageEnum) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:messageEnum)
    }

    static {
      defaultInstance = new messageEnum(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:messageEnum)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messageEnum_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messageEnum_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023proto/message.proto\"@\n\013messageEnum\"1\n\t" +
      "MessageID\022\021\n\014C_USER_LOGIN\020\221N\022\021\n\014S_USER_L" +
      "OGIN\020\222NB+\n\033com.jiang.framework.messageB\014" +
      "MessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_messageEnum_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_messageEnum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_messageEnum_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
